---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Add new
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: articles
  label: Articles
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Settings
- type: document
  path: theme.json
  label: Site Setting
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename::year::month:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
